export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as SkillsSection } from './SkillsSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as FeaturedSection } from './FeaturedSection'
export { default as TechStackSection } from './TechStackSection'
export { default as ContactSection } from './ContactSection'
export { default as Footer } from './Footer'
